---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:7.14.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: npm-install
  image: cypress/browsers:node14.15.0-chrome86-ff82
  commands: [npm ci]

- name: test
  image: cypress/browsers:node14.15.0-chrome86-ff82
  commands: ["npm run test:ci -s"]

- name: release
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  when:
    event: [push]

- name: publish-gh-pages
  image: plugins/gh-pages
  settings:
    pages_directory: examples/
    username: x-oauth-basic
    password:
      from_secret: GH_TOKEN
  when:
    event: [tag]

trigger:
  event: [push, tag]
---
kind: signature
hmac: 502c120397692f6acfa40a7faf03118348601d00a0a36a25b4aef0f1968d188f

...
