---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:8.47.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: install
  image: cypress/browsers:node16.5.0-chrome94-ff93
  commands: [npm ci]

- name: build
  image: cypress/browsers:node16.5.0-chrome94-ff93
  commands: ["npm run build -s"]
  depends_on: [install]

- name: test
  image: cypress/browsers:node16.5.0-chrome94-ff93
  commands: ["npm run test:ci -s"]
  depends_on: [install]

- name: release
  image: livingdocs/semantic-release:v1.2.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  when:
    event: [push]
  depends_on: [test]

- name: publish-gh-pages
  image: plugins/gh-pages
  settings:
    pages_directory: examples/
    username: x-oauth-basic
    password:
      from_secret: GH_TOKEN
  when:
    event: [tag]
  depends_on: [build]

trigger:
  event: [push, tag, pull_request]
---
kind: signature
hmac: fbd7cb3397c4f9cd9376301fbb2a72e10367cfeec9432c4c2098b2b1f0430f7e

...
