---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:9.1.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: install
  image: cypress/browsers:node16.5.0-chrome94-ff93
  commands: [npm ci]

- name: build
  image: cypress/browsers:node16.5.0-chrome94-ff93
  commands: ["npm run build -s"]
  depends_on: [install]

- name: test
  image: cypress/browsers:node16.5.0-chrome94-ff93
  commands: ["npm run test:ci -s"]
  depends_on: [install]

- name: release
  image: livingdocs/semantic-release:v1.2.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  when:
    event: [push]
  depends_on: [test]

- name: publish-gh-pages
  image: plugins/gh-pages
  settings:
    pages_directory: examples
    copy_contents: "true"
    username: x-oauth-basic
    password:
      from_secret: GH_TOKEN
  when:
    event: [tag]
  depends_on: [build]

trigger:
  event: [push, tag, pull_request]
---
kind: signature
hmac: da3c74532ef15d34138bf9d3a14261332a0cf67ad6f611f02c3ae3841b6005a2

...
